spring:
  datasource:
    # burada url/user vermiyoruz, testcontainers'tan geliyor
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none   # flyway kullandığın için
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  flyway:
    enabled: true
    # testte schema'yı sıfırlamak istersen:
    clean-disabled: false
    # prod'da gerekmez ama testte ilk migration'da sorun çıkarmaz
    baseline-on-migrate: true
    locations: classpath:db/migration
    # url/user/password'i AbstractPostgresIT veriyor

logging:
  level:
    org.flywaydb: info
    org.testcontainers: info
