spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:5432/Taskline}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}

  security:
    user:
      name: user
      password: 1234
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: true

logging:
  level:
    root: ${LOG_ROOT_LEVEL:INFO}
    org.hibernate.SQL: ${LOG_HIBERNATE_SQL:DEBUG}

server:
  port: ${SERVER_PORT:8080}
  ssl:
    enabled: false
